<?xml version="1.0" encoding="UTF-8"?>
<fpmd:simulation xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">
<uuid> 5F2136EC-30B1-11F1-AF36-6E0B6E29DCE2 </uuid>

                   ============================
                   I qbox rel1_78_4           I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I http://qboxcode.org      I
                   ============================


<release> rel1_78_4 macosx_homebrew  </release>
<user> erbai </user>
<sysname> Darwin </sysname>
<nodename> erbais-MacBook-Air.local </nodename>
<start_time> 2026-04-05T05:36:18Z </start_time>
 MPIdata::comm: 1x1x1x1
<mpi_processes count="1">
<process id="0"> erbais-MacBook-Air.local </process> (0,0,0,0)
</mpi_processes>
[qbox] <cmd># Qbox deck generated by the GDIS GTK4 Qbox tool.</cmd>
[qbox] <cmd># Coordinates and cell vectors are written in bohr.</cmd>
[qbox] <cmd># Local pseudo files and local restart XML files are staged into the job directory on Write Input / Run.</cmd>
[qbox] <cmd>set cell 32.49797356 0 0 0 31.98795537 0 0 0 30.23750773</cmd>
<unit_cell 
    a="32.49797356  0.00000000   0.00000000  "
    b="0.00000000   31.98795537  0.00000000  "
    c="0.00000000   0.00000000   30.23750773 " />
[qbox] <cmd>species o O_ONCV_PBE-1.2.xml</cmd>
  SpeciesCmd: defining species o as O_ONCV_PBE-1.2.xml

Warning at file , line 0, char 0
  Message: unable to open primary document entity '/Users/erbai/Desktop/gdismac/gtk4_rebuild/gtk4_app/qbox_jobs/water/species.xsd'

 species o:
<species name="o">
 <description>

 O_ONCV_PBE-1.2

 This pseudopotential file has been produced using the code
 ONCVPSP  (Optimized Norm-Conservinng Vanderbilt PSeudopotential)
 scalar-relativistic version 2.1.1, 03/26/2014 by D. R. Hamann
 The code is available through a link at URL www.mat-simresearch.com.
 Documentation with the package provides a full discription of the
 input data below.


 While it is not required under the terms of the GNU GPL, it is
 suggested that you cite D. R. Hamann, Phys. Rev. B 88, 085117 (2013)
 in any publication using these pseudopotentials.


 Copyright 2015 The Regents of the University of California
 
 This work is licensed under the Creative Commons Attribution-ShareAlike 
 4.0 International License. To view a copy of this license, visit 
 http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to 
 Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 
 This pseudopotential is part of the Schlipf-Gygi norm-conserving 
 pseudopotential library. Its construction parameters were tuned to 
 reproduce materials of a training set with very high accuracy and 
 should be suitable as a general purpose pseudopotential to treat a 
 variety of different compounds. For details of the construction and 
 testing of the pseudopotential please refer to:
 
 M. Schlipf, F. Gygi, Comp. Phys. Comm. 196, 36 (2015)
 http://dx.doi.org/10.1016/j.cpc.2015.05.011
 
 We kindly ask that you include this reference in all publications 
 associated to this pseudopotential.


Input file for PP generation:

# ATOM AND REFERENCE CONFIGURATION
# atsym  z    nc    nv    iexc   psfile
  O  8.00     1     2     4      fpmd
#
#   n    l    f        energy (Ha)
    1    0    2.00
    2    0    2.00
    2    1    4.00
#
# PSEUDOPOTENTIAL AND OPTIMIZATION
# lmax
    1
#
#   l,   rc,     ep,   ncon, nbas, qcut
    0   1.29195  -0.88057    5    8   8.98916
    1   1.47310  -0.33187    5    8   9.14990
#
# LOCAL POTENTIAL
# lloc, lpopt,  rc(5),   dvloc0
    4    5   0.90330      0.00000
#
# VANDERBILT-KLEINMAN-BYLANDER PROJECTORs
# l, nproj, debl
    0    2   1.51851
    1    2   1.53631
#
# MODEL CORE CHARGE
# icmod, fcfact
    0   0.00000
#
# LOG DERIVATIVE ANALYSIS
# epsh1, epsh2, depsh
   -5.00    3.00    0.02
#
# OUTPUT GRID
# rlmax, drl
    6.00    0.01
#
# TEST CONFIGURATIONS
# ncnf
    0
# nvcnf
#   n    l    f
 </description>
 <symbol>O</symbol>
 <atomic_number>8</atomic_number>
 <mass>15.99899960</mass>
 <norm_conserving_semilocal_pseudopotential>
 <valence_charge>6</valence_charge>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_semilocal_pseudopotential>
</species>
 SLPP semilocal potential
 rcps_ =   1.50000000
[qbox] <cmd>species h H_ONCV_PBE-1.2.xml</cmd>
  SpeciesCmd: defining species h as H_ONCV_PBE-1.2.xml

Warning at file , line 0, char 0
  Message: unable to open primary document entity '/Users/erbai/Desktop/gdismac/gtk4_rebuild/gtk4_app/qbox_jobs/water/species.xsd'

 species h:
<species name="h">
 <description>

 H_ONCV_PBE-1.2

 This pseudopotential file has been produced using the code
 ONCVPSP  (Optimized Norm-Conservinng Vanderbilt PSeudopotential)
 scalar-relativistic version 2.1.1, 03/26/2014 by D. R. Hamann
 The code is available through a link at URL www.mat-simresearch.com.
 Documentation with the package provides a full discription of the
 input data below.


 While it is not required under the terms of the GNU GPL, it is
 suggested that you cite D. R. Hamann, Phys. Rev. B 88, 085117 (2013)
 in any publication using these pseudopotentials.


 Copyright 2015 The Regents of the University of California
 
 This work is licensed under the Creative Commons Attribution-ShareAlike 
 4.0 International License. To view a copy of this license, visit 
 http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to 
 Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 
 This pseudopotential is part of the Schlipf-Gygi norm-conserving 
 pseudopotential library. Its construction parameters were tuned to 
 reproduce materials of a training set with very high accuracy and 
 should be suitable as a general purpose pseudopotential to treat a 
 variety of different compounds. For details of the construction and 
 testing of the pseudopotential please refer to:
 
 M. Schlipf, F. Gygi, Comp. Phys. Comm. 196, 36 (2015)
 http://dx.doi.org/10.1016/j.cpc.2015.05.011
 
 We kindly ask that you include this reference in all publications 
 associated to this pseudopotential.


Input file for PP generation:

# ATOM AND REFERENCE CONFIGURATION
# atsym  z    nc    nv    iexc   psfile
  H  1.00     0     1     4      fpmd
#
#   n    l    f        energy (Ha)
    1    0    1.00
#
# PSEUDOPOTENTIAL AND OPTIMIZATION
# lmax
    0
#
#   l,   rc,     ep,   ncon, nbas, qcut
    0   1.13748  -0.23860    5    8   9.72141
#
# LOCAL POTENTIAL
# lloc, lpopt,  rc(5),   dvloc0
    4    5   0.49352      0.00000
#
# VANDERBILT-KLEINMAN-BYLANDER PROJECTORs
# l, nproj, debl
    0    2   1.27464
#
# MODEL CORE CHARGE
# icmod, fcfact
    0   0.00000
#
# LOG DERIVATIVE ANALYSIS
# epsh1, epsh2, depsh
   -5.00    3.00    0.02
#
# OUTPUT GRID
# rlmax, drl
    6.00    0.01
#
# TEST CONFIGURATIONS
# ncnf
    0
# nvcnf
#   n    l    f
 </description>
 <symbol>H</symbol>
 <atomic_number>1</atomic_number>
 <mass>1.00800002</mass>
 <norm_conserving_semilocal_pseudopotential>
 <valence_charge>1</valence_charge>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_semilocal_pseudopotential>
</species>
 SLPP semilocal potential
 rcps_ =   1.50000000
[qbox] <cmd>atom O1 o 15.57131871 15.117809 15.117809</cmd>
[qbox] <cmd>atom H1 h 17.38016455 15.117809 15.117809</cmd>
[qbox] <cmd>atom H2 h 15.117809 16.87014637 15.117809</cmd>
[qbox] <cmd></cmd>
[qbox] <cmd>set xc PBE</cmd>
[qbox] <cmd>set ecut 35.0</cmd>
[qbox] <cmd>set scf_tol 1.0e-8</cmd>
[qbox] <cmd>set wf_dyn PSDA</cmd>
[qbox] <cmd>set atoms_dyn LOCKED</cmd>
[qbox] <cmd>set cell_dyn LOCKED</cmd>
[qbox] <cmd>randomize_wf</cmd>
[qbox] <cmd>run -atomic_density 0 40 10</cmd>
 EnergyFunctional: <np0v> 128 </np0v>  <np1v> 128 </np1v>  <np2v> 126 </np2v>
 EnergyFunctional: vft->np012(): 2064384
<wavefunction ecut="17.50000000" nspin="1" nel="8" nempty="0">
<cell a="32.497974 0.000000 0.000000"
      b="0.000000 31.987955 0.000000"
      c="0.000000 0.000000 30.237508"/>
 reciprocal lattice vectors
 0.193341 0.000000 0.000000
 0.000000 0.196423 0.000000
 0.000000 0.000000 0.207794
<refcell a="0.000000 0.000000 0.000000"
         b="0.000000 0.000000 0.000000"
         c="0.000000 0.000000 0.000000"/>
<grid nx="64" ny="64" nz="60"/>
<slater_determinant kpoint="0 0 0" size="4">
 sdcontext: 1x1
 basis size: 54999
 c dimensions: 54999x4   (54999x4 blocks)
 <density_matrix form="diagonal" size="4"/>
</slater_determinant>
</wavefunction>
<net_charge> 0 </net_charge>
<iteration count="1">
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  38.12476550 </eigenvalue_sum>
  <eigenvalue_sum>  28.58211894 </eigenvalue_sum>
  <eigenvalue_sum>  18.19772400 </eigenvalue_sum>
  <eigenvalue_sum>  9.51255403 </eigenvalue_sum>
  <eigenvalue_sum>  4.19145102 </eigenvalue_sum>
  <eigenvalue_sum>  4.02091168 </eigenvalue_sum>
  <eigenvalue_sum>  1.55728788 </eigenvalue_sum>
  <eigenvalue_sum>  1.41194228 </eigenvalue_sum>
  <eigenvalue_sum>  0.22521458 </eigenvalue_sum>
  <eigenvalue_sum>  -0.06821659 </eigenvalue_sum>
  <etotal_int>     -10.89169910 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -0.72671605 </eigenvalue_sum>
  <eigenvalue_sum>  -0.74170301 </eigenvalue_sum>
  <eigenvalue_sum>  -1.24957816 </eigenvalue_sum>
  <eigenvalue_sum>  -0.59377466 </eigenvalue_sum>
  <eigenvalue_sum>  -1.91524265 </eigenvalue_sum>
  <eigenvalue_sum>  -1.61509883 </eigenvalue_sum>
  <eigenvalue_sum>  -2.66783287 </eigenvalue_sum>
  <eigenvalue_sum>  -3.03810227 </eigenvalue_sum>
  <eigenvalue_sum>  -3.61095904 </eigenvalue_sum>
  <eigenvalue_sum>  -4.01262026 </eigenvalue_sum>
  <etotal_int>     -13.26274999 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -4.35921534 </eigenvalue_sum>
  <eigenvalue_sum>  -4.73248827 </eigenvalue_sum>
  <eigenvalue_sum>  -5.03150430 </eigenvalue_sum>
  <eigenvalue_sum>  -5.38851635 </eigenvalue_sum>
  <eigenvalue_sum>  -5.69098553 </eigenvalue_sum>
  <eigenvalue_sum>  -5.81987233 </eigenvalue_sum>
  <eigenvalue_sum>  -5.90937133 </eigenvalue_sum>
  <eigenvalue_sum>  -5.99635269 </eigenvalue_sum>
  <eigenvalue_sum>  -6.07078264 </eigenvalue_sum>
  <eigenvalue_sum>  -6.11329130 </eigenvalue_sum>
  <etotal_int>     -17.30259320 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -5.78080388 </eigenvalue_sum>
  <eigenvalue_sum>  -5.83466275 </eigenvalue_sum>
  <eigenvalue_sum>  -5.89806037 </eigenvalue_sum>
  <eigenvalue_sum>  -5.97556726 </eigenvalue_sum>
  <eigenvalue_sum>  -6.06960393 </eigenvalue_sum>
  <eigenvalue_sum>  -6.17890280 </eigenvalue_sum>
  <eigenvalue_sum>  -6.29738621 </eigenvalue_sum>
  <eigenvalue_sum>  -6.45441584 </eigenvalue_sum>
  <eigenvalue_sum>  -6.74540952 </eigenvalue_sum>
  <eigenvalue_sum>  -6.80440393 </eigenvalue_sum>
  <etotal_int>     -19.16803357 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -6.80840107 </eigenvalue_sum>
  <eigenvalue_sum>  -6.80996580 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81175276 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81189706 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81196232 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81197356 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81198001 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81198139 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81198215 </eigenvalue_sum>
  <eigenvalue_sum>  -6.81198239 </eigenvalue_sum>
  <etotal_int>     -19.18770166 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -7.08727610 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08787488 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08842962 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08852489 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08857170 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08857734 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08857912 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08857961 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08857992 </eigenvalue_sum>
  <eigenvalue_sum>  -7.08858004 </eigenvalue_sum>
  <etotal_int>     -19.45574990 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -3.29186301 </eigenvalue_sum>
  <eigenvalue_sum>  -3.39099939 </eigenvalue_sum>
  <eigenvalue_sum>  -3.51300136 </eigenvalue_sum>
  <eigenvalue_sum>  -3.53407300 </eigenvalue_sum>
  <eigenvalue_sum>  -3.55633737 </eigenvalue_sum>
  <eigenvalue_sum>  -3.55955550 </eigenvalue_sum>
  <eigenvalue_sum>  -3.56129556 </eigenvalue_sum>
  <eigenvalue_sum>  -3.56156565 </eigenvalue_sum>
  <eigenvalue_sum>  -3.56176365 </eigenvalue_sum>
  <eigenvalue_sum>  -3.56182391 </eigenvalue_sum>
  <etotal_int>     -17.10605331 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.68300563 </eigenvalue_sum>
  <eigenvalue_sum>  -2.68938418 </eigenvalue_sum>
  <eigenvalue_sum>  -2.69765024 </eigenvalue_sum>
  <eigenvalue_sum>  -2.69924522 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70083470 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70108724 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70122098 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70124691 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70126663 </eigenvalue_sum>
  <eigenvalue_sum>  -2.70127418 </eigenvalue_sum>
  <etotal_int>     -16.95644849 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.54742970 </eigenvalue_sum>
  <eigenvalue_sum>  -2.54997440 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55198251 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55216665 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55232689 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55236990 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55240939 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55242118 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55242939 </eigenvalue_sum>
  <eigenvalue_sum>  -2.55243172 </eigenvalue_sum>
  <etotal_int>     -16.94964433 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.25400736 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25546645 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25699998 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25720618 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25740812 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25744847 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25747594 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25748231 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25748701 </eigenvalue_sum>
  <eigenvalue_sum>  -2.25748856 </eigenvalue_sum>
  <etotal_int>     -16.93016661 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.33391111 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33416507 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33446558 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33453306 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33459228 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33460263 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33460705 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33460806 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33460882 </eigenvalue_sum>
  <eigenvalue_sum>  -2.33460918 </eigenvalue_sum>
  <etotal_int>     -16.93030335 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.27011209 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27013332 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27015870 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016355 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016750 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016835 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016884 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016896 </eigenvalue_sum>
  <eigenvalue_sum>  -2.27016902 </eigenvalue_sum>
  <etotal_int>     -16.92827099 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.19174068 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19176374 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19178476 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19178849 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19179112 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19179172 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19179214 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19179227 </eigenvalue_sum>
  <eigenvalue_sum>  -2.19179234 </eigenvalue_sum>
  <etotal_int>     -16.92671989 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.11690499 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11692320 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11694298 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11694731 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11695098 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11695183 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11695237 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11695250 </eigenvalue_sum>
  <eigenvalue_sum>  -2.11695258 </eigenvalue_sum>
  <etotal_int>     -16.92621440 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.10308772 </eigenvalue_sum>
  <eigenvalue_sum>  -2.10309036 </eigenvalue_sum>
  <eigenvalue_sum>  -2.10309216 </eigenvalue_sum>
  <eigenvalue_sum>  -2.10309246 </eigenvalue_sum>
  <eigenvalue_sum>  -2.10309273 </eigenvalue_sum>
  <eigenvalue_sum>  -2.10309280 </eigenvalue_sum>
  <etotal_int>     -16.92641368 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.08970113 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08970840 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971395 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971530 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971686 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971719 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971740 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08971745 </eigenvalue_sum>
  <etotal_int>     -16.92686531 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.08910627 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08910745 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08910841 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08910857 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08910871 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08910873 </eigenvalue_sum>
  <etotal_int>     -16.92696560 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.08691211 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08691291 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08691357 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08691373 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08691391 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08691396 </eigenvalue_sum>
  <etotal_int>     -16.92707543 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.08550125 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08550151 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08550174 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08550180 </eigenvalue_sum>
  <etotal_int>     -16.92714789 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.08260182 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08260204 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08260221 </eigenvalue_sum>
  <eigenvalue_sum>  -2.08260224 </eigenvalue_sum>
  <etotal_int>     -16.92724565 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07788048 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07788087 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07788125 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07788133 </eigenvalue_sum>
  <etotal_int>     -16.92730317 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07312503 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07312520 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07312535 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07312537 </eigenvalue_sum>
  <etotal_int>     -16.92737553 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07110938 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07110954 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07110976 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07110981 </eigenvalue_sum>
  <etotal_int>     -16.92744725 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07052897 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07052900 </eigenvalue_sum>
  <etotal_int>     -16.92747545 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07017993 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07017994 </eigenvalue_sum>
  <etotal_int>     -16.92750147 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07028747 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07028747 </eigenvalue_sum>
  <etotal_int>     -16.92752436 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07089107 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07089109 </eigenvalue_sum>
  <etotal_int>     -16.92754063 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07102503 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07102504 </eigenvalue_sum>
  <etotal_int>     -16.92754269 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07129661 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07129662 </eigenvalue_sum>
  <etotal_int>     -16.92754605 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07145173 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07145173 </eigenvalue_sum>
  <etotal_int>     -16.92754685 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07153342 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07153343 </eigenvalue_sum>
  <etotal_int>     -16.92754737 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07148809 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07148810 </eigenvalue_sum>
  <etotal_int>     -16.92754802 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07154261 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07154261 </eigenvalue_sum>
  <etotal_int>     -16.92754824 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07159138 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07159138 </eigenvalue_sum>
  <etotal_int>     -16.92754856 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07156104 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07156104 </eigenvalue_sum>
  <etotal_int>     -16.92754875 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07155962 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07155962 </eigenvalue_sum>
  <etotal_int>     -16.92754941 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07157696 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07157696 </eigenvalue_sum>
  <etotal_int>     -16.92754959 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07157090 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07157090 </eigenvalue_sum>
  <etotal_int>     -16.92754966 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07158227 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07158227 </eigenvalue_sum>
  <etotal_int>     -16.92754970 </etotal_int>
  BOSampleStepper: end scf iteration
  BOSampleStepper: start scf iteration
  <electronic_charge ispin="0"> 8.00000000 </electronic_charge>
  <eigenvalue_sum>  -2.07158588 </eigenvalue_sum>
  <eigenvalue_sum>  -2.07158588 </eigenvalue_sum>
  <etotal_int>     -16.92754972 </etotal_int>
  BOSampleStepper: end scf iteration
  <ekin>        11.59123762 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -16.70111620 </eps>
  <enl>         -0.46631767 </enl>
  <ecoul>       -7.18140617 </ecoul>
  <exc>         -4.16994732 </exc>
  <esr>          1.52978065 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -16.92754974 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -16.92754974 </enthalpy>
<atomset>
<unit_cell 
    a=" 32.49797356   0.00000000   0.00000000"
    b="  0.00000000  31.98795537   0.00000000"
    c="  0.00000000   0.00000000  30.23750773" />
  <atom name="O1" species="o">
    <position> 15.57131871 15.11780900 15.11780900 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.02949050 -0.03771988 -0.00001597 </force>
  </atom>
  <atom name="H1" species="h">
    <position> 17.38016455 15.11780900 15.11780900 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.03651056 0.00222825 -0.00000018 </force>
  </atom>
  <atom name="H2" species="h">
    <position> 15.11780900 16.87014637 15.11780900 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.00683264 0.03524847 -0.00000024 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 32.497974 </unit_cell_a_norm>
<unit_cell_b_norm> 31.987955 </unit_cell_b_norm>
<unit_cell_c_norm> 30.237508 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 31433.212 </unit_cell_volume>
<timing name="iteration"       min="48.803" max="48.803"/>
</iteration>
<timing name="charge"          min="3.964" max="3.964"/>
<timing name="energy"          min="24.874" max="24.874"/>
<timing name="ortho_align"     min="0.283" max="0.283"/>
<timing name="psda_prec"       min="0.080" max="0.080"/>
<timing name="psda_residual"   min="0.151" max="0.151"/>
<timing name="psda_update_wf"  min="0.167" max="0.167"/>
<timing name="update_vhxc"     min="17.356" max="17.356"/>
<timing name="wf_update"       min="0.723" max="0.723"/>
<timing name="ekin"            min="0.041" max="0.041"/>
<timing name="exc"             min="15.662" max="15.662"/>
<timing name="hpsi"            min="23.347" max="23.347"/>
<timing name="nonlocal"        min="1.475" max="1.475"/>
<timing name="charge_compute"  min="2.222" max="2.222"/>
<timing name="charge_integral" min="0.323" max="0.323"/>
<timing name="charge_rowsum"   min="0.038" max="0.038"/>
<timing name="charge_vft"      min="1.376" max="1.376"/>
[qbox] <cmd>save water.xml</cmd>
 SampleWriter: write time: 0.018 s
 SampleWriter: file size: 10732497
 SampleWriter: aggregate write rate: 554.25 MB/s
[qbox]  End of command stream 
<real_time> 49.11 </real_time>
<end_time> 2026-04-05T05:37:07Z </end_time>
</fpmd:simulation>
