# --- gdis Makefile for modern macOS

CC ?= cc
CFLAGS = -O2
LDFLAGS = -headerpad_max_install_names
LIBS += -framework AppKit

all: gdis

gdis.app:
	../scripts/build_macos_portable.py --skip-build --no-dmg --no-zip

gdis.dmg:
	../scripts/build_macos_portable.py --skip-build --no-zip

gdis.zip:
	../scripts/build_macos_portable.py --skip-build --no-dmg
